controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use yii\data\Pagination;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Monuments;
use app\models\MonumentsSearch;
use app\models\Types;
use app\models\Districts;
use yii\helpers\ArrayHelper;
use yii\widgets\ListView;
use yii\data\ActiveDataProvider; 

class SiteController extends Controller
{    
    /**
     * @inheritdoc
     */
    var $session;
    public function init() 
    {
        $this->session = Yii::$app->session;
    }
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $types=Types::find()->all();
        
        return $this->render('index',['types'=>$types]);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }  
        
         $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
    public function actionLaw()
    {
        return $this->render('law');
    }
     public function actionStatistic()
    {

        $districts=Districts::find()->all();
        return $this->render('statistic',['districts'=>'districts']);
    }
    /*public function actionNew()

    {
         $types=ArrayHelper::map(Types::find()->all(),'id','name');
        $districts=ArrayHelper::map(Districts::find()->all(),'id','name');
      
        $searchModel = new MonumentsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->post());

        return $this->render('new', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,'types'=>$types,'districts'=>$districts
        ]);
    }*/
     public function actionList()

    {
       


        // build a DB query to get all articles with status = 1
        

         //$selectedType=$monument->type->id;
            $view='list';
         $types=ArrayHelper::map(Types::find()->all(),'id','name');
         $districts=ArrayHelper::map(Districts::find()->all(),'id','name');
         $searchModel = new MonumentsSearch();
        
         if(array_key_exists('view',Yii::$app->request->get()))
            {
                $view=Yii::$app->request->get('view');
            }
        if(Yii::$app->request->isPost)
            {
                //var_dump(Yii::$app->request->post());die;

                if(array_key_exists('filter_reset',Yii::$app->request->post()))
                    {
                        $this->removeSessionVar();
                        $query = Monuments::find();
                    }
                else if(array_key_exists('filter',Yii::$app->request->post()))
                    {                       
                        if(Yii::$app->request->post('type')!='')                
                            $type=Yii::$app->request->post('type');
                            $selectedType=$type;

                            if(Yii::$app->request->post('district')!='') 
                            $district=Yii::$app->request->post('district');
                            $selectedDistrict= $district ;

                            $query=Monuments::getFilter($type,$district);

                            $this->setSessionVar($type,$district);
                 }
                



            }
        else if(isset($this->session['type']) ||  isset($this->session['district']))
         {
            $type = $this->session->get('type');
            $district = $this->session->get('district');

            $selectedType=$type;
            $selectedDistrict= $district ;

            $query=Monuments::getFilter($type,$district);


         }


            else $query = Monuments::find();

            

            $popular= Monuments::getPopular(3);

            $recent= Monuments::getRecent(3);

            $data = Monuments::getAll($query,2);

        return $this->render('list',['pagination'=>$data['pagination'], 'monuments'=>$data['monuments'],'popular'=>$popular,'recent'=>$recent,'types'=>$types,'districts'=>$districts,'selectedType'=>$selectedType, 'selectedDistrict'=>$selectedDistrict,'view'=>$view]);

    }

    function setSessionVar($type,$district)
    {
        $this->session->set('type', $type);
        $this->session->set('district', $district);
    }
   
    function removeSessionVar()
    {
        $this->session->remove('type');
        $this->session->remove('district');
    }

   
    
    public function actionDetail($id)
    {
         $popular= Monuments::getPopular(3);
        $recent= Monuments::getRecent(3);
        //var_dump($id);die;
        $monument=Monuments::findOne($id);
        //var_dump($monument);die;
        return $this->render('detail',['monument_detail'=>$monument,'popular'=>$popular,'recent'=>$recent]);
    }
    public function actionTable()
    {
        return $this->render('table');
    }
}

views/layouts/admin.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */



AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/admin/index']],
            ['label' => 'Памятки', 'url' => ['/admin/monuments/index']],
            ['label' => 'Додати', 'url' => ['/admin/districts/index']],
            ['label' => 'Значення', 'url' => ['/admin/meanings/index']],
            ['label' => 'Тип Памятки', 'url' => ['/admin/types/index']],
            ['label' => 'Адміністратори', 'url' => ['/admin/types/index']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\assets\PublicAsset;
use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use yii\widgets\Menu;
use app\assets\AppAsset;
use yii\widgets\ActiveForm;
use app\models\Admins;
use app\components\ModalLoginForm;

PublicAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div id="bg1"></div>
        <div id="bg2"></div>
        <div id="outer">
            <div id="header">
                <div id="logo">
                    <h1>
                        <a href="index.php">Облік Пам'яток культури Миколаївщини    </a>
                    </h1>
                </div>
                <div id="search">
                    <form name="search" method="post" action="search.php">
                        <div>
                            <input type="search" class="text" name="query" size="32" maxlength="128" />
                        </div>
                    </form>
                </div>
                <nav class="menu_top">
                    <ul>
                        <li >
                            <?= Html::a('Головна', ['site/index']) ?>                            
                        </li>
                            
                        <li>
                            <?= Html::a('Каталог Пам\'яток', ['site/list']) ?> 
                            
                        </li>
                        <li>
                            <?= Html::a('Статистика', ['site/statistic']) ?> 
                            
                        </li>
                        <li>
                            <?= Html::a('Законодавство', ['site/law']) ?>
                        </li>                       
                        <li>
                            <?= Html::a('Про сайт', ['site/about']) ?>
                        </li>
                        <?if (!(Yii::$app->user->isGuest)) { echo ('<li>'. Html::a('Додати Пам\'ятку', ['admin/']).'</li>'); } ?>
                        <li class="login">
                            <i class="fa fa-user" aria-hidden="true"></i><?if(Yii::$app->user->isGuest){?><a href="auth/login">Авторизуватися</a><?php } 
                            else 
                            {?>
                               <a href="auth/logout">Вийти</a>
                            <?}

                            ?>
                        </li>
                    </ul><br class="clear" />
                </nav>
               
            </div>
            <div id="banner">
                <div class="captions">
                    <h2>Культурна спадщина Миколаєва</h2>
                </div>
                <div class="slider">
                <ul>
                    <li><img src="/public/images/admin.jpg" alt=""></li>
                    <li><img src="/public/images/admin.jpg" alt=""></li>
                    <li><img src="/public/images/admin.jpg" alt=""></li>
                    <li><img src="/public/images/admin.jpg" alt=""></li>
                    <li><img src="/public/images/admin.jpg" alt=""></li>
                </ul>
            </div>
                
            </div>
            <div id="main">

                
<?= $content ?>
            
            </div>  
</div>
        
        <footer id="main_footer">
            <div class="footer_inner">@copy right MTU</div>
        </footer>

           

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>